server:
  port: 8796

spring:
  datasource:
  ## localhost:
    password: 1111
    username: root
#  ## serer:
#    password: cins
#    username: dataCastle
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cins_data_castle?verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf8
  mail:
    host: smtp.163.com
    password: Bangnicayanlei59
    username: yangquan95@163.com
    properties:
     mail:
      smtp:
       auth:
       starttls:
                 enable: true
                 required: true
  aop:
    auto: true
    proxy-target-class: true


mybatis:
  type-aliases-package: cn.edu.swpu.cins.data_castle.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    use-column-label: true
    map-underscore-to-camel-case: true

############## Data_Castle Config ##############

data_castle:
   server:
     host: 182.150.37.58
     port: 2017
   path:
        user:
           enable: dataCastle/user/enable
   answer:
     location: /opt/data-castle/match-answer
#     location: /home/yang/file
     limitTime: 86400
     captchaExpires: 180

logging:
  file: data-castle.log
  level: info

endpoints:
  shutdown:
    enabled: true
    sensitive: false
    path: /shutdown
  actuator:


security:
  user:
    name: muyi
    password: yang

management:
  port: 8796
  address: 127.0.0.1



